### ISSUE TITLE
its messing up my game

### ISSUE THREAD

**Issue by iSyed0** [wxrayut/ArenaOfValor-Skin-Changer#1]
its not working for me. i followed everything down, but after replacing the folders the game stops viewing heroes/skins and the interface becomes extremely laggy

**Comment by wxrayut** [comment]
idk. 😅

**Comment by tranqm54** [comment]
Vì sao nó làm hỏng trò chơi của bạn?
Vào 19:30, Th 2, 5 thg 2, 2024 Rhya ***@***.***> đã viết:

**Comment by wxrayut** [comment]
english please.

**Comment by tranqm54** [comment]
Vui lòng nói tiếng việt, because tui ko biết English

Vào 19:41, Th 2, 5 thg 2, 2024 Rhya ***@***.***> đã viết:
