### ISSUE TITLE
How to get new skin lists?

### ISSUE THREAD

**Issue by Polonetincr** [wxrayut/ArenaOfValor-Skin-Changer#2]
### What happened?

How to get new skin lists?

**Comment by wxrayut** [comment]
I will not updates or enhancements for this tool anymore, as someones is selling my tool.

**Comment by tranqm54** [comment]
Bạn cứ mod bình thường thôi,y như bạn mod skin thường á

Vào 19:28, Th 2, 5 thg 2, 2024 Rhya ***@***.***> đã viết:
